version: '4.0'

services:
  gateway-service:
    container_name: gateway_service 
    build: ./
    ports:
      - "8000:8000"
    networks:
      - gmail_network
    depends_on:
      - redis
      - minio

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - gmail_network

  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    volumes:
      - minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'user'
      MINIO_ROOT_PASSWORD: 'password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data
    networks:
      - gmail_network

networks:
  gmail_network:
    external: true
    name: gmail_network
    driver: bridge

volumes:
  redis-data:
  minio: