// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.1
// source: gmailapp-submodule/attachment.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttachmentCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileUrl  string `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileName string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize string `protobuf:"bytes,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MimeType string `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
}

func (x *AttachmentCreateReq) Reset() {
	*x = AttachmentCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_attachment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachmentCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentCreateReq) ProtoMessage() {}

func (x *AttachmentCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_attachment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentCreateReq.ProtoReflect.Descriptor instead.
func (*AttachmentCreateReq) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_attachment_proto_rawDescGZIP(), []int{0}
}

func (x *AttachmentCreateReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AttachmentCreateReq) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *AttachmentCreateReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AttachmentCreateReq) GetFileSize() string {
	if x != nil {
		return x.FileSize
	}
	return ""
}

func (x *AttachmentCreateReq) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type AttachmentGetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileUrl  string `protobuf:"bytes,3,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileName string `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType string `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileSize string `protobuf:"bytes,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
}

func (x *AttachmentGetRes) Reset() {
	*x = AttachmentGetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_attachment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachmentGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentGetRes) ProtoMessage() {}

func (x *AttachmentGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_attachment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentGetRes.ProtoReflect.Descriptor instead.
func (*AttachmentGetRes) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_attachment_proto_rawDescGZIP(), []int{1}
}

func (x *AttachmentGetRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttachmentGetRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AttachmentGetRes) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *AttachmentGetRes) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AttachmentGetRes) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *AttachmentGetRes) GetFileSize() string {
	if x != nil {
		return x.FileSize
	}
	return ""
}

type AttachmentGetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutboxId string `protobuf:"bytes,1,opt,name=outbox_id,json=outboxId,proto3" json:"outbox_id,omitempty"`
}

func (x *AttachmentGetAllReq) Reset() {
	*x = AttachmentGetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_attachment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachmentGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentGetAllReq) ProtoMessage() {}

func (x *AttachmentGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_attachment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentGetAllReq.ProtoReflect.Descriptor instead.
func (*AttachmentGetAllReq) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_attachment_proto_rawDescGZIP(), []int{2}
}

func (x *AttachmentGetAllReq) GetOutboxId() string {
	if x != nil {
		return x.OutboxId
	}
	return ""
}

type AttachmentGetAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attachments []*AttachmentGetRes `protobuf:"bytes,1,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Pagination  *Pagination         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *AttachmentGetAllRes) Reset() {
	*x = AttachmentGetAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_attachment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachmentGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentGetAllRes) ProtoMessage() {}

func (x *AttachmentGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_attachment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentGetAllRes.ProtoReflect.Descriptor instead.
func (*AttachmentGetAllRes) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_attachment_proto_rawDescGZIP(), []int{3}
}

func (x *AttachmentGetAllRes) GetAttachments() []*AttachmentGetRes {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *AttachmentGetAllRes) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type AttachmentCreateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId  string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileUrl string `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
}

func (x *AttachmentCreateRes) Reset() {
	*x = AttachmentCreateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_attachment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachmentCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentCreateRes) ProtoMessage() {}

func (x *AttachmentCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_attachment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentCreateRes.ProtoReflect.Descriptor instead.
func (*AttachmentCreateRes) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_attachment_proto_rawDescGZIP(), []int{4}
}

func (x *AttachmentCreateRes) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *AttachmentCreateRes) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

type AttachmentDeleteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *AttachmentDeleteRes) Reset() {
	*x = AttachmentDeleteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_attachment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachmentDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentDeleteRes) ProtoMessage() {}

func (x *AttachmentDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_attachment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentDeleteRes.ProtoReflect.Descriptor instead.
func (*AttachmentDeleteRes) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_attachment_proto_rawDescGZIP(), []int{5}
}

func (x *AttachmentDeleteRes) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

var File_gmailapp_submodule_attachment_proto protoreflect.FileDescriptor

var file_gmailapp_submodule_attachment_proto_rawDesc = []byte{
	0x0a, 0x23, 0x67, 0x6d, 0x61, 0x69, 0x6c, 0x61, 0x70, 0x70, 0x2d, 0x73, 0x75, 0x62, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x2f, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x1d, 0x67,
	0x6d, 0x61, 0x69, 0x6c, 0x61, 0x70, 0x70, 0x2d, 0x73, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x2f, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x01, 0x0a,
	0x13, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22,
	0xad, 0x01, 0x0a, 0x10, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22,
	0x32, 0x0a, 0x13, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x78,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x62, 0x6f,
	0x78, 0x49, 0x64, 0x22, 0x85, 0x01, 0x0a, 0x13, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x0b, 0x61,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x6d, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x49, 0x0a, 0x13, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66,
	0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x32, 0x0a, 0x13, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x1b, 0x0a,
	0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0xbe, 0x02, 0x0a, 0x11, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x42, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x12,
	0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x44, 0x1a, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x42, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x4d, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x12, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x44, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x33, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x44, 0x1a, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x42, 0x18, 0x5a, 0x16, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gmailapp_submodule_attachment_proto_rawDescOnce sync.Once
	file_gmailapp_submodule_attachment_proto_rawDescData = file_gmailapp_submodule_attachment_proto_rawDesc
)

func file_gmailapp_submodule_attachment_proto_rawDescGZIP() []byte {
	file_gmailapp_submodule_attachment_proto_rawDescOnce.Do(func() {
		file_gmailapp_submodule_attachment_proto_rawDescData = protoimpl.X.CompressGZIP(file_gmailapp_submodule_attachment_proto_rawDescData)
	})
	return file_gmailapp_submodule_attachment_proto_rawDescData
}

var file_gmailapp_submodule_attachment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gmailapp_submodule_attachment_proto_goTypes = []any{
	(*AttachmentCreateReq)(nil), // 0: protos.AttachmentCreateReq
	(*AttachmentGetRes)(nil),    // 1: protos.AttachmentGetRes
	(*AttachmentGetAllReq)(nil), // 2: protos.AttachmentGetAllReq
	(*AttachmentGetAllRes)(nil), // 3: protos.AttachmentGetAllRes
	(*AttachmentCreateRes)(nil), // 4: protos.AttachmentCreateRes
	(*AttachmentDeleteRes)(nil), // 5: protos.AttachmentDeleteRes
	(*Pagination)(nil),          // 6: protos.Pagination
	(*ByID)(nil),                // 7: protos.ByID
}
var file_gmailapp_submodule_attachment_proto_depIdxs = []int32{
	1, // 0: protos.AttachmentGetAllRes.attachments:type_name -> protos.AttachmentGetRes
	6, // 1: protos.AttachmentGetAllRes.pagination:type_name -> protos.Pagination
	0, // 2: protos.AttachmentService.Create:input_type -> protos.AttachmentCreateReq
	7, // 3: protos.AttachmentService.GetByID:input_type -> protos.ByID
	2, // 4: protos.AttachmentService.GetAll:input_type -> protos.AttachmentGetAllReq
	7, // 5: protos.AttachmentService.GetMyUploads:input_type -> protos.ByID
	7, // 6: protos.AttachmentService.Delete:input_type -> protos.ByID
	4, // 7: protos.AttachmentService.Create:output_type -> protos.AttachmentCreateRes
	1, // 8: protos.AttachmentService.GetByID:output_type -> protos.AttachmentGetRes
	3, // 9: protos.AttachmentService.GetAll:output_type -> protos.AttachmentGetAllRes
	3, // 10: protos.AttachmentService.GetMyUploads:output_type -> protos.AttachmentGetAllRes
	5, // 11: protos.AttachmentService.Delete:output_type -> protos.AttachmentDeleteRes
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gmailapp_submodule_attachment_proto_init() }
func file_gmailapp_submodule_attachment_proto_init() {
	if File_gmailapp_submodule_attachment_proto != nil {
		return
	}
	file_gmailapp_submodule_void_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gmailapp_submodule_attachment_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AttachmentCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmailapp_submodule_attachment_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AttachmentGetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmailapp_submodule_attachment_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AttachmentGetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmailapp_submodule_attachment_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AttachmentGetAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmailapp_submodule_attachment_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AttachmentCreateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmailapp_submodule_attachment_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*AttachmentDeleteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gmailapp_submodule_attachment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gmailapp_submodule_attachment_proto_goTypes,
		DependencyIndexes: file_gmailapp_submodule_attachment_proto_depIdxs,
		MessageInfos:      file_gmailapp_submodule_attachment_proto_msgTypes,
	}.Build()
	File_gmailapp_submodule_attachment_proto = out.File
	file_gmailapp_submodule_attachment_proto_rawDesc = nil
	file_gmailapp_submodule_attachment_proto_goTypes = nil
	file_gmailapp_submodule_attachment_proto_depIdxs = nil
}
