// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.1
// source: gmailapp-submodule/outbox.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutboxMessageSentBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject       string     `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string     `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Receivers     *Receivers `protobuf:"bytes,4,opt,name=receivers,proto3" json:"receivers,omitempty"`
	AttachmentIds []string   `protobuf:"bytes,5,rep,name=attachment_ids,json=attachmentIds,proto3" json:"attachment_ids,omitempty"`
}

func (x *OutboxMessageSentBody) Reset() {
	*x = OutboxMessageSentBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_outbox_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutboxMessageSentBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxMessageSentBody) ProtoMessage() {}

func (x *OutboxMessageSentBody) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_outbox_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxMessageSentBody.ProtoReflect.Descriptor instead.
func (*OutboxMessageSentBody) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_outbox_proto_rawDescGZIP(), []int{0}
}

func (x *OutboxMessageSentBody) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *OutboxMessageSentBody) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *OutboxMessageSentBody) GetReceivers() *Receivers {
	if x != nil {
		return x.Receivers
	}
	return nil
}

func (x *OutboxMessageSentBody) GetAttachmentIds() []string {
	if x != nil {
		return x.AttachmentIds
	}
	return nil
}

type OutboxMessageSentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body     *OutboxMessageSentBody `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	SenderId string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
}

func (x *OutboxMessageSentReq) Reset() {
	*x = OutboxMessageSentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_outbox_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutboxMessageSentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxMessageSentReq) ProtoMessage() {}

func (x *OutboxMessageSentReq) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_outbox_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxMessageSentReq.ProtoReflect.Descriptor instead.
func (*OutboxMessageSentReq) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_outbox_proto_rawDescGZIP(), []int{1}
}

func (x *OutboxMessageSentReq) GetBody() *OutboxMessageSentBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *OutboxMessageSentReq) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type OutboxMessageGetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject       string      `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string      `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Sender        *UserGetRes `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Receivers     *Receivers  `protobuf:"bytes,5,opt,name=receivers,proto3" json:"receivers,omitempty"`
	AttachmentIds []string    `protobuf:"bytes,6,rep,name=attachment_ids,json=attachmentIds,proto3" json:"attachment_ids,omitempty"`
	IsDraft       bool        `protobuf:"varint,7,opt,name=is_draft,json=isDraft,proto3" json:"is_draft,omitempty"`
	IsArchived    bool        `protobuf:"varint,8,opt,name=is_archived,json=isArchived,proto3" json:"is_archived,omitempty"`
	IsStarred     bool        `protobuf:"varint,9,opt,name=is_starred,json=isStarred,proto3" json:"is_starred,omitempty"`
	SentAt        string      `protobuf:"bytes,10,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	DeletedAt     string      `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *OutboxMessageGetRes) Reset() {
	*x = OutboxMessageGetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_outbox_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutboxMessageGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxMessageGetRes) ProtoMessage() {}

func (x *OutboxMessageGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_outbox_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxMessageGetRes.ProtoReflect.Descriptor instead.
func (*OutboxMessageGetRes) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_outbox_proto_rawDescGZIP(), []int{2}
}

func (x *OutboxMessageGetRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutboxMessageGetRes) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *OutboxMessageGetRes) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *OutboxMessageGetRes) GetSender() *UserGetRes {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *OutboxMessageGetRes) GetReceivers() *Receivers {
	if x != nil {
		return x.Receivers
	}
	return nil
}

func (x *OutboxMessageGetRes) GetAttachmentIds() []string {
	if x != nil {
		return x.AttachmentIds
	}
	return nil
}

func (x *OutboxMessageGetRes) GetIsDraft() bool {
	if x != nil {
		return x.IsDraft
	}
	return false
}

func (x *OutboxMessageGetRes) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

func (x *OutboxMessageGetRes) GetIsStarred() bool {
	if x != nil {
		return x.IsStarred
	}
	return false
}

func (x *OutboxMessageGetRes) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *OutboxMessageGetRes) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type OutboxMessagesGetAllBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query      string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	IsArchived bool   `protobuf:"varint,2,opt,name=is_archived,json=isArchived,proto3" json:"is_archived,omitempty"`
	IsStarred  bool   `protobuf:"varint,3,opt,name=is_starred,json=isStarred,proto3" json:"is_starred,omitempty"`
	SentFrom   string `protobuf:"bytes,4,opt,name=sent_from,json=sentFrom,proto3" json:"sent_from,omitempty"`
	SentTo     string `protobuf:"bytes,5,opt,name=sent_to,json=sentTo,proto3" json:"sent_to,omitempty"`
}

func (x *OutboxMessagesGetAllBody) Reset() {
	*x = OutboxMessagesGetAllBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_outbox_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutboxMessagesGetAllBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxMessagesGetAllBody) ProtoMessage() {}

func (x *OutboxMessagesGetAllBody) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_outbox_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxMessagesGetAllBody.ProtoReflect.Descriptor instead.
func (*OutboxMessagesGetAllBody) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_outbox_proto_rawDescGZIP(), []int{3}
}

func (x *OutboxMessagesGetAllBody) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *OutboxMessagesGetAllBody) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

func (x *OutboxMessagesGetAllBody) GetIsStarred() bool {
	if x != nil {
		return x.IsStarred
	}
	return false
}

func (x *OutboxMessagesGetAllBody) GetSentFrom() string {
	if x != nil {
		return x.SentFrom
	}
	return ""
}

func (x *OutboxMessagesGetAllBody) GetSentTo() string {
	if x != nil {
		return x.SentTo
	}
	return ""
}

type OutboxMessagesGetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body       *OutboxMessagesGetAllBody `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Pagination *Pagination               `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *OutboxMessagesGetAllReq) Reset() {
	*x = OutboxMessagesGetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_outbox_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutboxMessagesGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxMessagesGetAllReq) ProtoMessage() {}

func (x *OutboxMessagesGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_outbox_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxMessagesGetAllReq.ProtoReflect.Descriptor instead.
func (*OutboxMessagesGetAllReq) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_outbox_proto_rawDescGZIP(), []int{4}
}

func (x *OutboxMessagesGetAllReq) GetBody() *OutboxMessagesGetAllBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *OutboxMessagesGetAllReq) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type OutboxMessagesGetAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*OutboxMessageGetRes `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *OutboxMessagesGetAllRes) Reset() {
	*x = OutboxMessagesGetAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_outbox_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutboxMessagesGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxMessagesGetAllRes) ProtoMessage() {}

func (x *OutboxMessagesGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_outbox_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxMessagesGetAllRes.ProtoReflect.Descriptor instead.
func (*OutboxMessagesGetAllRes) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_outbox_proto_rawDescGZIP(), []int{5}
}

func (x *OutboxMessagesGetAllRes) GetMessages() []*OutboxMessageGetRes {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Receivers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To  *MessageSendTo  `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Cc  *MessageSendCC  `protobuf:"bytes,3,opt,name=cc,proto3" json:"cc,omitempty"`
	Bcc *MessageSendBCC `protobuf:"bytes,4,opt,name=bcc,proto3" json:"bcc,omitempty"`
}

func (x *Receivers) Reset() {
	*x = Receivers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_outbox_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Receivers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receivers) ProtoMessage() {}

func (x *Receivers) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_outbox_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receivers.ProtoReflect.Descriptor instead.
func (*Receivers) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_outbox_proto_rawDescGZIP(), []int{6}
}

func (x *Receivers) GetTo() *MessageSendTo {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Receivers) GetCc() *MessageSendCC {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *Receivers) GetBcc() *MessageSendBCC {
	if x != nil {
		return x.Bcc
	}
	return nil
}

type MessageSendTo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emails []string `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
}

func (x *MessageSendTo) Reset() {
	*x = MessageSendTo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_outbox_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendTo) ProtoMessage() {}

func (x *MessageSendTo) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_outbox_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendTo.ProtoReflect.Descriptor instead.
func (*MessageSendTo) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_outbox_proto_rawDescGZIP(), []int{7}
}

func (x *MessageSendTo) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

type MessageSendCC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emails []string `protobuf:"bytes,2,rep,name=emails,proto3" json:"emails,omitempty"`
}

func (x *MessageSendCC) Reset() {
	*x = MessageSendCC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_outbox_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendCC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendCC) ProtoMessage() {}

func (x *MessageSendCC) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_outbox_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendCC.ProtoReflect.Descriptor instead.
func (*MessageSendCC) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_outbox_proto_rawDescGZIP(), []int{8}
}

func (x *MessageSendCC) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

type MessageSendBCC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emails []string `protobuf:"bytes,2,rep,name=emails,proto3" json:"emails,omitempty"`
}

func (x *MessageSendBCC) Reset() {
	*x = MessageSendBCC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_outbox_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendBCC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendBCC) ProtoMessage() {}

func (x *MessageSendBCC) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_outbox_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendBCC.ProtoReflect.Descriptor instead.
func (*MessageSendBCC) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_outbox_proto_rawDescGZIP(), []int{9}
}

func (x *MessageSendBCC) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

type MessageSentRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalSent    int64    `protobuf:"varint,1,opt,name=total_sent,json=totalSent,proto3" json:"total_sent,omitempty"`
	TotalFailed  int64    `protobuf:"varint,2,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	FailedEmails []string `protobuf:"bytes,3,rep,name=failed_emails,json=failedEmails,proto3" json:"failed_emails,omitempty"`
}

func (x *MessageSentRes) Reset() {
	*x = MessageSentRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmailapp_submodule_outbox_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSentRes) ProtoMessage() {}

func (x *MessageSentRes) ProtoReflect() protoreflect.Message {
	mi := &file_gmailapp_submodule_outbox_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSentRes.ProtoReflect.Descriptor instead.
func (*MessageSentRes) Descriptor() ([]byte, []int) {
	return file_gmailapp_submodule_outbox_proto_rawDescGZIP(), []int{10}
}

func (x *MessageSentRes) GetTotalSent() int64 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *MessageSentRes) GetTotalFailed() int64 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *MessageSentRes) GetFailedEmails() []string {
	if x != nil {
		return x.FailedEmails
	}
	return nil
}

var File_gmailapp_submodule_outbox_proto protoreflect.FileDescriptor

var file_gmailapp_submodule_outbox_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x67, 0x6d, 0x61, 0x69, 0x6c, 0x61, 0x70, 0x70, 0x2d, 0x73, 0x75, 0x62, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x2f, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x1d, 0x67, 0x6d, 0x61, 0x69, 0x6c,
	0x61, 0x70, 0x70, 0x2d, 0x73, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x76, 0x6f,
	0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x67, 0x6d, 0x61, 0x69, 0x6c, 0x61,
	0x70, 0x70, 0x2d, 0x73, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9d, 0x01, 0x0a, 0x15, 0x4f, 0x75, 0x74, 0x62,
	0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x74, 0x42, 0x6f, 0x64,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12,
	0x2f, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x73, 0x52, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x12, 0x25, 0x0a, 0x0e, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x22, 0x66, 0x0a, 0x14, 0x4f, 0x75, 0x74, 0x62, 0x6f,
	0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x31, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22,
	0xea, 0x02, 0x0a, 0x13, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x2f, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x73, 0x52, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f,
	0x64, 0x72, 0x61, 0x66, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x44,
	0x72, 0x61, 0x66, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x61, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x72,
	0x72, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x74, 0x61,
	0x72, 0x72, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x74, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xa6, 0x01, 0x0a,
	0x18, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12,
	0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x72, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x74, 0x61, 0x72, 0x72, 0x65, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x17, 0x0a, 0x07,
	0x73, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x6e, 0x74, 0x54, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x17, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x78,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x34, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x64,
	0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x32, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x52, 0x0a, 0x17, 0x4f,
	0x75, 0x74, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22,
	0x83, 0x01, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x73, 0x12, 0x25, 0x0a,
	0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f,
	0x52, 0x02, 0x74, 0x6f, 0x12, 0x25, 0x0a, 0x02, 0x63, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x43, 0x52, 0x02, 0x63, 0x63, 0x12, 0x28, 0x0a, 0x03, 0x62,
	0x63, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x43, 0x43,
	0x52, 0x03, 0x62, 0x63, 0x63, 0x22, 0x27, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x27,
	0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x43, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x28, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x43, 0x43, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x73, 0x22, 0x77, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x65,
	0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x66, 0x61, 0x69, 0x6c,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x46,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x5f,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x32, 0xf5, 0x02, 0x0a, 0x0d, 0x4f,
	0x75, 0x74, 0x62, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x04,
	0x53, 0x65, 0x6e, 0x64, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4f, 0x75,
	0x74, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x03, 0x47, 0x65,
	0x74, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x44, 0x1a,
	0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x4a, 0x0a, 0x06,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x4f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x65,
	0x54, 0x6f, 0x54, 0x72, 0x61, 0x73, 0x68, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x42, 0x79, 0x49, 0x44, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56,
	0x6f, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x44, 0x1a, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x0b, 0x53, 0x74, 0x61,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x42, 0x79, 0x49, 0x44, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x56, 0x6f, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x0e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x42, 0x79, 0x49, 0x44, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x6f,
	0x69, 0x64, 0x42, 0x18, 0x5a, 0x16, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gmailapp_submodule_outbox_proto_rawDescOnce sync.Once
	file_gmailapp_submodule_outbox_proto_rawDescData = file_gmailapp_submodule_outbox_proto_rawDesc
)

func file_gmailapp_submodule_outbox_proto_rawDescGZIP() []byte {
	file_gmailapp_submodule_outbox_proto_rawDescOnce.Do(func() {
		file_gmailapp_submodule_outbox_proto_rawDescData = protoimpl.X.CompressGZIP(file_gmailapp_submodule_outbox_proto_rawDescData)
	})
	return file_gmailapp_submodule_outbox_proto_rawDescData
}

var file_gmailapp_submodule_outbox_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_gmailapp_submodule_outbox_proto_goTypes = []any{
	(*OutboxMessageSentBody)(nil),    // 0: protos.OutboxMessageSentBody
	(*OutboxMessageSentReq)(nil),     // 1: protos.OutboxMessageSentReq
	(*OutboxMessageGetRes)(nil),      // 2: protos.OutboxMessageGetRes
	(*OutboxMessagesGetAllBody)(nil), // 3: protos.OutboxMessagesGetAllBody
	(*OutboxMessagesGetAllReq)(nil),  // 4: protos.OutboxMessagesGetAllReq
	(*OutboxMessagesGetAllRes)(nil),  // 5: protos.OutboxMessagesGetAllRes
	(*Receivers)(nil),                // 6: protos.Receivers
	(*MessageSendTo)(nil),            // 7: protos.MessageSendTo
	(*MessageSendCC)(nil),            // 8: protos.MessageSendCC
	(*MessageSendBCC)(nil),           // 9: protos.MessageSendBCC
	(*MessageSentRes)(nil),           // 10: protos.MessageSentRes
	(*UserGetRes)(nil),               // 11: protos.UserGetRes
	(*Pagination)(nil),               // 12: protos.Pagination
	(*ByID)(nil),                     // 13: protos.ByID
	(*Void)(nil),                     // 14: protos.Void
}
var file_gmailapp_submodule_outbox_proto_depIdxs = []int32{
	6,  // 0: protos.OutboxMessageSentBody.receivers:type_name -> protos.Receivers
	0,  // 1: protos.OutboxMessageSentReq.body:type_name -> protos.OutboxMessageSentBody
	11, // 2: protos.OutboxMessageGetRes.sender:type_name -> protos.UserGetRes
	6,  // 3: protos.OutboxMessageGetRes.receivers:type_name -> protos.Receivers
	3,  // 4: protos.OutboxMessagesGetAllReq.body:type_name -> protos.OutboxMessagesGetAllBody
	12, // 5: protos.OutboxMessagesGetAllReq.pagination:type_name -> protos.Pagination
	2,  // 6: protos.OutboxMessagesGetAllRes.messages:type_name -> protos.OutboxMessageGetRes
	7,  // 7: protos.Receivers.to:type_name -> protos.MessageSendTo
	8,  // 8: protos.Receivers.cc:type_name -> protos.MessageSendCC
	9,  // 9: protos.Receivers.bcc:type_name -> protos.MessageSendBCC
	1,  // 10: protos.OutboxService.Send:input_type -> protos.OutboxMessageSentReq
	13, // 11: protos.OutboxService.Get:input_type -> protos.ByID
	4,  // 12: protos.OutboxService.GetAll:input_type -> protos.OutboxMessagesGetAllReq
	13, // 13: protos.OutboxService.MoveToTrash:input_type -> protos.ByID
	13, // 14: protos.OutboxService.Delete:input_type -> protos.ByID
	13, // 15: protos.OutboxService.StarMessage:input_type -> protos.ByID
	13, // 16: protos.OutboxService.ArchiveMessage:input_type -> protos.ByID
	10, // 17: protos.OutboxService.Send:output_type -> protos.MessageSentRes
	2,  // 18: protos.OutboxService.Get:output_type -> protos.OutboxMessageGetRes
	5,  // 19: protos.OutboxService.GetAll:output_type -> protos.OutboxMessagesGetAllRes
	14, // 20: protos.OutboxService.MoveToTrash:output_type -> protos.Void
	14, // 21: protos.OutboxService.Delete:output_type -> protos.Void
	14, // 22: protos.OutboxService.StarMessage:output_type -> protos.Void
	14, // 23: protos.OutboxService.ArchiveMessage:output_type -> protos.Void
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_gmailapp_submodule_outbox_proto_init() }
func file_gmailapp_submodule_outbox_proto_init() {
	if File_gmailapp_submodule_outbox_proto != nil {
		return
	}
	file_gmailapp_submodule_void_proto_init()
	file_gmailapp_submodule_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gmailapp_submodule_outbox_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*OutboxMessageSentBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmailapp_submodule_outbox_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*OutboxMessageSentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmailapp_submodule_outbox_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*OutboxMessageGetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmailapp_submodule_outbox_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*OutboxMessagesGetAllBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmailapp_submodule_outbox_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*OutboxMessagesGetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmailapp_submodule_outbox_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*OutboxMessagesGetAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmailapp_submodule_outbox_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Receivers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmailapp_submodule_outbox_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*MessageSendTo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmailapp_submodule_outbox_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*MessageSendCC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmailapp_submodule_outbox_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*MessageSendBCC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmailapp_submodule_outbox_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*MessageSentRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gmailapp_submodule_outbox_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gmailapp_submodule_outbox_proto_goTypes,
		DependencyIndexes: file_gmailapp_submodule_outbox_proto_depIdxs,
		MessageInfos:      file_gmailapp_submodule_outbox_proto_msgTypes,
	}.Build()
	File_gmailapp_submodule_outbox_proto = out.File
	file_gmailapp_submodule_outbox_proto_rawDesc = nil
	file_gmailapp_submodule_outbox_proto_goTypes = nil
	file_gmailapp_submodule_outbox_proto_depIdxs = nil
}
